# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Combat_perdu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Combat_perdu(object):
    def setupUi(self, Combat_perdu):
        Combat_perdu.setObjectName("Combat_perdu")
        Combat_perdu.resize(586, 367)
        Combat_perdu.setMinimumSize(QtCore.QSize(586, 367))
        Combat_perdu.setMaximumSize(QtCore.QSize(586, 367))
        self.Ensemble_combat_perdu = QtWidgets.QGroupBox(Combat_perdu)
        self.Ensemble_combat_perdu.setGeometry(QtCore.QRect(0, -30, 611, 491))
        self.Ensemble_combat_perdu.setTitle("")
        self.Ensemble_combat_perdu.setObjectName("Ensemble_combat_perdu")
        self.PASS = QtWidgets.QCommandLinkButton(self.Ensemble_combat_perdu)
        self.PASS.setGeometry(QtCore.QRect(460, 270, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PASS.setFont(font)
        self.PASS.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Pass.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PASS.setIcon(icon)
        self.PASS.setIconSize(QtCore.QSize(100, 100))
        self.PASS.setObjectName("PASS")
        self.Pika_triste = QtWidgets.QLabel(self.Ensemble_combat_perdu)
        self.Pika_triste.setGeometry(QtCore.QRect(80, 90, 331, 301))
        self.Pika_triste.setText("")
        self.Pika_triste.setPixmap(QtGui.QPixmap("../Images/Defaite.jpg"))
        self.Pika_triste.setScaledContents(True)
        self.Pika_triste.setObjectName("Pika_triste")
        self.Arriere = QtWidgets.QLabel(self.Ensemble_combat_perdu)
        self.Arriere.setGeometry(QtCore.QRect(-10, 20, 631, 451))
        self.Arriere.setStyleSheet("background-color: rgba(248, 232, 206);")
        self.Arriere.setText("")
        self.Arriere.setObjectName("Arriere")
        self.label_2 = QtWidgets.QLabel(self.Ensemble_combat_perdu)
        self.label_2.setGeometry(QtCore.QRect(-10, 30, 601, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Arriere.raise_()
        self.PASS.raise_()
        self.Pika_triste.raise_()
        self.label_2.raise_()

        self.retranslateUi(Combat_perdu)
        QtCore.QMetaObject.connectSlotsByName(Combat_perdu)

    def retranslateUi(self, Combat_perdu):
        _translate = QtCore.QCoreApplication.translate
        Combat_perdu.setWindowTitle(_translate("Combat_perdu", "Defaite"))
        self.label_2.setText(_translate("Combat_perdu", "Perdu  !!!!"))
