# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Victoire_combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Victoire_combat(object):
    def setupUi(self, Victoire_combat):
        Victoire_combat.setObjectName("Victoire_combat")
        Victoire_combat.resize(586, 367)
        Victoire_combat.setMinimumSize(QtCore.QSize(586, 367))
        Victoire_combat.setMaximumSize(QtCore.QSize(586, 367))
        self.Ensemble_Victoire = QtWidgets.QGroupBox(Victoire_combat)
        self.Ensemble_Victoire.setGeometry(QtCore.QRect(-11, -1, 601, 381))
        self.Ensemble_Victoire.setTitle("")
        self.Ensemble_Victoire.setObjectName("Ensemble_Victoire")
        self.label = QtWidgets.QLabel(self.Ensemble_Victoire)
        self.label.setGeometry(QtCore.QRect(200, 110, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Arriere = QtWidgets.QLabel(self.Ensemble_Victoire)
        self.Arriere.setGeometry(QtCore.QRect(10, -10, 591, 381))
        self.Arriere.setText("")
        self.Arriere.setPixmap(QtGui.QPixmap("../Images_interface/Victoire.jpg"))
        self.Arriere.setScaledContents(True)
        self.Arriere.setObjectName("Arriere")
        self.PASS = QtWidgets.QCommandLinkButton(self.Ensemble_Victoire)
        self.PASS.setGeometry(QtCore.QRect(480, 250, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PASS.setFont(font)
        self.PASS.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images_interface/Pass.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PASS.setIcon(icon)
        self.PASS.setIconSize(QtCore.QSize(100, 100))
        self.PASS.setObjectName("PASS")
        self.Arriere.raise_()
        self.label.raise_()
        self.PASS.raise_()

        self.retranslateUi(Victoire_combat)
        QtCore.QMetaObject.connectSlotsByName(Victoire_combat)

    def retranslateUi(self, Victoire_combat):
        _translate = QtCore.QCoreApplication.translate
        Victoire_combat.setWindowTitle(_translate("Victoire_combat", "Dialog"))
        self.label.setText(_translate("Victoire_combat", "Victoire !!!"))
