# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Capture_pokemon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 545)
        font = QtGui.QFont()
        font.setPointSize(30)
        Dialog.setFont(font)
        self.Pokemon_Capture = QtWidgets.QLabel(Dialog)
        self.Pokemon_Capture.setGeometry(QtCore.QRect(0, -10, 781, 561))
        self.Pokemon_Capture.setText("")
        self.Pokemon_Capture.setPixmap(QtGui.QPixmap("../Images_interface/Capture.png"))
        self.Pokemon_Capture.setScaledContents(True)
        self.Pokemon_Capture.setObjectName("Pokemon_Capture")
        self.Pokemon_Attrape = QtWidgets.QLabel(Dialog)
        self.Pokemon_Attrape.setGeometry(QtCore.QRect(300, 140, 181, 181))
        self.Pokemon_Attrape.setText("")
        self.Pokemon_Attrape.setScaledContents(True)
        self.Pokemon_Attrape.setObjectName("Pokemon_Attrape")
        self.Affichage = QtWidgets.QLabel(Dialog)
        self.Affichage.setGeometry(QtCore.QRect(180, 330, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Affichage.setFont(font)
        self.Affichage.setTextFormat(QtCore.Qt.AutoText)
        self.Affichage.setScaledContents(False)
        self.Affichage.setObjectName("Affichage")
        self.Affichage_2 = QtWidgets.QLabel(Dialog)
        self.Affichage_2.setGeometry(QtCore.QRect(290, 50, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Affichage_2.setFont(font)
        self.Affichage_2.setObjectName("Affichage_2")
        self.Nom_pokemon = QtWidgets.QLabel(Dialog)
        self.Nom_pokemon.setGeometry(QtCore.QRect(190, 370, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Nom_pokemon.setFont(font)
        self.Nom_pokemon.setText("")
        self.Nom_pokemon.setAlignment(QtCore.Qt.AlignCenter)
        self.Nom_pokemon.setObjectName("Nom_pokemon")
        self.PASS = QtWidgets.QCommandLinkButton(Dialog)
        self.PASS.setGeometry(QtCore.QRect(600, 410, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PASS.setFont(font)
        self.PASS.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images_interface/Pass.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PASS.setIcon(icon)
        self.PASS.setIconSize(QtCore.QSize(100, 100))
        self.PASS.setObjectName("PASS")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Affichage.setText(_translate("Dialog", "Vous avez attrapé"))
        self.Affichage_2.setText(_translate("Dialog", "Bravo !!!"))
